/*
Llama Stack Specification

Testing ScoringFunctionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ScoringFunctionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ScoringFunctionsAPIService V1ScoringFunctionsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ScoringFunctionsAPI.V1ScoringFunctionsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScoringFunctionsAPIService V1ScoringFunctionsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ScoringFunctionsAPI.V1ScoringFunctionsPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ScoringFunctionsAPIService V1ScoringFunctionsScoringFnIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var scoringFnId string

		resp, httpRes, err := apiClient.ScoringFunctionsAPI.V1ScoringFunctionsScoringFnIdGet(context.Background(), scoringFnId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
