/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListToolGroupsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListToolGroupsResponse{}

// ListToolGroupsResponse struct for ListToolGroupsResponse
type ListToolGroupsResponse struct {
	Data []ToolGroup `json:"data"`
}

type _ListToolGroupsResponse ListToolGroupsResponse

// NewListToolGroupsResponse instantiates a new ListToolGroupsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListToolGroupsResponse(data []ToolGroup) *ListToolGroupsResponse {
	this := ListToolGroupsResponse{}
	this.Data = data
	return &this
}

// NewListToolGroupsResponseWithDefaults instantiates a new ListToolGroupsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListToolGroupsResponseWithDefaults() *ListToolGroupsResponse {
	this := ListToolGroupsResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListToolGroupsResponse) GetData() []ToolGroup {
	if o == nil {
		var ret []ToolGroup
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListToolGroupsResponse) GetDataOk() ([]ToolGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListToolGroupsResponse) SetData(v []ToolGroup) {
	o.Data = v
}

func (o ListToolGroupsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListToolGroupsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListToolGroupsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListToolGroupsResponse := _ListToolGroupsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListToolGroupsResponse)

	if err != nil {
		return err
	}

	*o = ListToolGroupsResponse(varListToolGroupsResponse)

	return err
}

type NullableListToolGroupsResponse struct {
	value *ListToolGroupsResponse
	isSet bool
}

func (v NullableListToolGroupsResponse) Get() *ListToolGroupsResponse {
	return v.value
}

func (v *NullableListToolGroupsResponse) Set(val *ListToolGroupsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListToolGroupsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListToolGroupsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListToolGroupsResponse(val *ListToolGroupsResponse) *NullableListToolGroupsResponse {
	return &NullableListToolGroupsResponse{value: val, isSet: true}
}

func (v NullableListToolGroupsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListToolGroupsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


