/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostTrainingJob1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTrainingJob1{}

// PostTrainingJob1 struct for PostTrainingJob1
type PostTrainingJob1 struct {
	JobUuid string `json:"job_uuid"`
}

type _PostTrainingJob1 PostTrainingJob1

// NewPostTrainingJob1 instantiates a new PostTrainingJob1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTrainingJob1(jobUuid string) *PostTrainingJob1 {
	this := PostTrainingJob1{}
	this.JobUuid = jobUuid
	return &this
}

// NewPostTrainingJob1WithDefaults instantiates a new PostTrainingJob1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTrainingJob1WithDefaults() *PostTrainingJob1 {
	this := PostTrainingJob1{}
	return &this
}

// GetJobUuid returns the JobUuid field value
func (o *PostTrainingJob1) GetJobUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobUuid
}

// GetJobUuidOk returns a tuple with the JobUuid field value
// and a boolean to check if the value has been set.
func (o *PostTrainingJob1) GetJobUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobUuid, true
}

// SetJobUuid sets field value
func (o *PostTrainingJob1) SetJobUuid(v string) {
	o.JobUuid = v
}

func (o PostTrainingJob1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTrainingJob1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_uuid"] = o.JobUuid
	return toSerialize, nil
}

func (o *PostTrainingJob1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostTrainingJob1 := _PostTrainingJob1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostTrainingJob1)

	if err != nil {
		return err
	}

	*o = PostTrainingJob1(varPostTrainingJob1)

	return err
}

type NullablePostTrainingJob1 struct {
	value *PostTrainingJob1
	isSet bool
}

func (v NullablePostTrainingJob1) Get() *PostTrainingJob1 {
	return v.value
}

func (v *NullablePostTrainingJob1) Set(val *PostTrainingJob1) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTrainingJob1) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTrainingJob1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTrainingJob1(val *PostTrainingJob1) *NullablePostTrainingJob1 {
	return &NullablePostTrainingJob1{value: val, isSet: true}
}

func (v NullablePostTrainingJob1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTrainingJob1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


