/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QATFinetuningConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QATFinetuningConfig{}

// QATFinetuningConfig struct for QATFinetuningConfig
type QATFinetuningConfig struct {
	Type string `json:"type"`
	QuantizerName string `json:"quantizer_name"`
	GroupSize int32 `json:"group_size"`
}

type _QATFinetuningConfig QATFinetuningConfig

// NewQATFinetuningConfig instantiates a new QATFinetuningConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQATFinetuningConfig(type_ string, quantizerName string, groupSize int32) *QATFinetuningConfig {
	this := QATFinetuningConfig{}
	this.Type = type_
	this.QuantizerName = quantizerName
	this.GroupSize = groupSize
	return &this
}

// NewQATFinetuningConfigWithDefaults instantiates a new QATFinetuningConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQATFinetuningConfigWithDefaults() *QATFinetuningConfig {
	this := QATFinetuningConfig{}
	var type_ string = "QAT"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *QATFinetuningConfig) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *QATFinetuningConfig) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *QATFinetuningConfig) SetType(v string) {
	o.Type = v
}

// GetQuantizerName returns the QuantizerName field value
func (o *QATFinetuningConfig) GetQuantizerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuantizerName
}

// GetQuantizerNameOk returns a tuple with the QuantizerName field value
// and a boolean to check if the value has been set.
func (o *QATFinetuningConfig) GetQuantizerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuantizerName, true
}

// SetQuantizerName sets field value
func (o *QATFinetuningConfig) SetQuantizerName(v string) {
	o.QuantizerName = v
}

// GetGroupSize returns the GroupSize field value
func (o *QATFinetuningConfig) GetGroupSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GroupSize
}

// GetGroupSizeOk returns a tuple with the GroupSize field value
// and a boolean to check if the value has been set.
func (o *QATFinetuningConfig) GetGroupSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupSize, true
}

// SetGroupSize sets field value
func (o *QATFinetuningConfig) SetGroupSize(v int32) {
	o.GroupSize = v
}

func (o QATFinetuningConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QATFinetuningConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["quantizer_name"] = o.QuantizerName
	toSerialize["group_size"] = o.GroupSize
	return toSerialize, nil
}

func (o *QATFinetuningConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"quantizer_name",
		"group_size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQATFinetuningConfig := _QATFinetuningConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQATFinetuningConfig)

	if err != nil {
		return err
	}

	*o = QATFinetuningConfig(varQATFinetuningConfig)

	return err
}

type NullableQATFinetuningConfig struct {
	value *QATFinetuningConfig
	isSet bool
}

func (v NullableQATFinetuningConfig) Get() *QATFinetuningConfig {
	return v.value
}

func (v *NullableQATFinetuningConfig) Set(val *QATFinetuningConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableQATFinetuningConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableQATFinetuningConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQATFinetuningConfig(val *QATFinetuningConfig) *NullableQATFinetuningConfig {
	return &NullableQATFinetuningConfig{value: val, isSet: true}
}

func (v NullableQATFinetuningConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQATFinetuningConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


