/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryTracesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryTracesResponse{}

// QueryTracesResponse struct for QueryTracesResponse
type QueryTracesResponse struct {
	Data []Trace `json:"data"`
}

type _QueryTracesResponse QueryTracesResponse

// NewQueryTracesResponse instantiates a new QueryTracesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryTracesResponse(data []Trace) *QueryTracesResponse {
	this := QueryTracesResponse{}
	this.Data = data
	return &this
}

// NewQueryTracesResponseWithDefaults instantiates a new QueryTracesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryTracesResponseWithDefaults() *QueryTracesResponse {
	this := QueryTracesResponse{}
	return &this
}

// GetData returns the Data field value
func (o *QueryTracesResponse) GetData() []Trace {
	if o == nil {
		var ret []Trace
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *QueryTracesResponse) GetDataOk() ([]Trace, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *QueryTracesResponse) SetData(v []Trace) {
	o.Data = v
}

func (o QueryTracesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryTracesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *QueryTracesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryTracesResponse := _QueryTracesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryTracesResponse)

	if err != nil {
		return err
	}

	*o = QueryTracesResponse(varQueryTracesResponse)

	return err
}

type NullableQueryTracesResponse struct {
	value *QueryTracesResponse
	isSet bool
}

func (v NullableQueryTracesResponse) Get() *QueryTracesResponse {
	return v.value
}

func (v *NullableQueryTracesResponse) Set(val *QueryTracesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryTracesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryTracesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryTracesResponse(val *QueryTracesResponse) *NullableQueryTracesResponse {
	return &NullableQueryTracesResponse{value: val, isSet: true}
}

func (v NullableQueryTracesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryTracesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


