/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenAIAssistantMessageParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenAIAssistantMessageParam{}

// OpenAIAssistantMessageParam A message containing the model's (assistant) response in an OpenAI-compatible chat completion request.
type OpenAIAssistantMessageParam struct {
	// Must be \"assistant\" to identify this as the model's response
	Role string `json:"role"`
	Content *OpenAIAssistantMessageParamContent `json:"content,omitempty"`
	// (Optional) The name of the assistant message participant.
	Name *string `json:"name,omitempty"`
	// List of tool calls. Each tool call is an OpenAIChatCompletionToolCall object.
	ToolCalls []OpenAIChatCompletionToolCall `json:"tool_calls,omitempty"`
}

type _OpenAIAssistantMessageParam OpenAIAssistantMessageParam

// NewOpenAIAssistantMessageParam instantiates a new OpenAIAssistantMessageParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenAIAssistantMessageParam(role string) *OpenAIAssistantMessageParam {
	this := OpenAIAssistantMessageParam{}
	this.Role = role
	return &this
}

// NewOpenAIAssistantMessageParamWithDefaults instantiates a new OpenAIAssistantMessageParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenAIAssistantMessageParamWithDefaults() *OpenAIAssistantMessageParam {
	this := OpenAIAssistantMessageParam{}
	var role string = "assistant"
	this.Role = role
	return &this
}

// GetRole returns the Role field value
func (o *OpenAIAssistantMessageParam) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *OpenAIAssistantMessageParam) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *OpenAIAssistantMessageParam) SetRole(v string) {
	o.Role = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *OpenAIAssistantMessageParam) GetContent() OpenAIAssistantMessageParamContent {
	if o == nil || IsNil(o.Content) {
		var ret OpenAIAssistantMessageParamContent
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAIAssistantMessageParam) GetContentOk() (*OpenAIAssistantMessageParamContent, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *OpenAIAssistantMessageParam) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given OpenAIAssistantMessageParamContent and assigns it to the Content field.
func (o *OpenAIAssistantMessageParam) SetContent(v OpenAIAssistantMessageParamContent) {
	o.Content = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OpenAIAssistantMessageParam) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAIAssistantMessageParam) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OpenAIAssistantMessageParam) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OpenAIAssistantMessageParam) SetName(v string) {
	o.Name = &v
}

// GetToolCalls returns the ToolCalls field value if set, zero value otherwise.
func (o *OpenAIAssistantMessageParam) GetToolCalls() []OpenAIChatCompletionToolCall {
	if o == nil || IsNil(o.ToolCalls) {
		var ret []OpenAIChatCompletionToolCall
		return ret
	}
	return o.ToolCalls
}

// GetToolCallsOk returns a tuple with the ToolCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAIAssistantMessageParam) GetToolCallsOk() ([]OpenAIChatCompletionToolCall, bool) {
	if o == nil || IsNil(o.ToolCalls) {
		return nil, false
	}
	return o.ToolCalls, true
}

// HasToolCalls returns a boolean if a field has been set.
func (o *OpenAIAssistantMessageParam) HasToolCalls() bool {
	if o != nil && !IsNil(o.ToolCalls) {
		return true
	}

	return false
}

// SetToolCalls gets a reference to the given []OpenAIChatCompletionToolCall and assigns it to the ToolCalls field.
func (o *OpenAIAssistantMessageParam) SetToolCalls(v []OpenAIChatCompletionToolCall) {
	o.ToolCalls = v
}

func (o OpenAIAssistantMessageParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenAIAssistantMessageParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ToolCalls) {
		toSerialize["tool_calls"] = o.ToolCalls
	}
	return toSerialize, nil
}

func (o *OpenAIAssistantMessageParam) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenAIAssistantMessageParam := _OpenAIAssistantMessageParam{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenAIAssistantMessageParam)

	if err != nil {
		return err
	}

	*o = OpenAIAssistantMessageParam(varOpenAIAssistantMessageParam)

	return err
}

type NullableOpenAIAssistantMessageParam struct {
	value *OpenAIAssistantMessageParam
	isSet bool
}

func (v NullableOpenAIAssistantMessageParam) Get() *OpenAIAssistantMessageParam {
	return v.value
}

func (v *NullableOpenAIAssistantMessageParam) Set(val *OpenAIAssistantMessageParam) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenAIAssistantMessageParam) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenAIAssistantMessageParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenAIAssistantMessageParam(val *OpenAIAssistantMessageParam) *NullableOpenAIAssistantMessageParam {
	return &NullableOpenAIAssistantMessageParam{value: val, isSet: true}
}

func (v NullableOpenAIAssistantMessageParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenAIAssistantMessageParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


