/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentToolGroupWithArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentToolGroupWithArgs{}

// AgentToolGroupWithArgs struct for AgentToolGroupWithArgs
type AgentToolGroupWithArgs struct {
	Name string `json:"name"`
	Args map[string]AppendRowsRequestRowsInnerValue `json:"args"`
}

type _AgentToolGroupWithArgs AgentToolGroupWithArgs

// NewAgentToolGroupWithArgs instantiates a new AgentToolGroupWithArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentToolGroupWithArgs(name string, args map[string]AppendRowsRequestRowsInnerValue) *AgentToolGroupWithArgs {
	this := AgentToolGroupWithArgs{}
	this.Name = name
	this.Args = args
	return &this
}

// NewAgentToolGroupWithArgsWithDefaults instantiates a new AgentToolGroupWithArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentToolGroupWithArgsWithDefaults() *AgentToolGroupWithArgs {
	this := AgentToolGroupWithArgs{}
	return &this
}

// GetName returns the Name field value
func (o *AgentToolGroupWithArgs) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgentToolGroupWithArgs) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgentToolGroupWithArgs) SetName(v string) {
	o.Name = v
}

// GetArgs returns the Args field value
func (o *AgentToolGroupWithArgs) GetArgs() map[string]AppendRowsRequestRowsInnerValue {
	if o == nil {
		var ret map[string]AppendRowsRequestRowsInnerValue
		return ret
	}

	return o.Args
}

// GetArgsOk returns a tuple with the Args field value
// and a boolean to check if the value has been set.
func (o *AgentToolGroupWithArgs) GetArgsOk() (map[string]AppendRowsRequestRowsInnerValue, bool) {
	if o == nil {
		return map[string]AppendRowsRequestRowsInnerValue{}, false
	}
	return o.Args, true
}

// SetArgs sets field value
func (o *AgentToolGroupWithArgs) SetArgs(v map[string]AppendRowsRequestRowsInnerValue) {
	o.Args = v
}

func (o AgentToolGroupWithArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentToolGroupWithArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["args"] = o.Args
	return toSerialize, nil
}

func (o *AgentToolGroupWithArgs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"args",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentToolGroupWithArgs := _AgentToolGroupWithArgs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentToolGroupWithArgs)

	if err != nil {
		return err
	}

	*o = AgentToolGroupWithArgs(varAgentToolGroupWithArgs)

	return err
}

type NullableAgentToolGroupWithArgs struct {
	value *AgentToolGroupWithArgs
	isSet bool
}

func (v NullableAgentToolGroupWithArgs) Get() *AgentToolGroupWithArgs {
	return v.value
}

func (v *NullableAgentToolGroupWithArgs) Set(val *AgentToolGroupWithArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentToolGroupWithArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentToolGroupWithArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentToolGroupWithArgs(val *AgentToolGroupWithArgs) *NullableAgentToolGroupWithArgs {
	return &NullableAgentToolGroupWithArgs{value: val, isSet: true}
}

func (v NullableAgentToolGroupWithArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentToolGroupWithArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


