/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListModelsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListModelsResponse{}

// ListModelsResponse struct for ListModelsResponse
type ListModelsResponse struct {
	Data []Model `json:"data"`
}

type _ListModelsResponse ListModelsResponse

// NewListModelsResponse instantiates a new ListModelsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListModelsResponse(data []Model) *ListModelsResponse {
	this := ListModelsResponse{}
	this.Data = data
	return &this
}

// NewListModelsResponseWithDefaults instantiates a new ListModelsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListModelsResponseWithDefaults() *ListModelsResponse {
	this := ListModelsResponse{}
	return &this
}

// GetData returns the Data field value
func (o *ListModelsResponse) GetData() []Model {
	if o == nil {
		var ret []Model
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListModelsResponse) GetDataOk() ([]Model, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListModelsResponse) SetData(v []Model) {
	o.Data = v
}

func (o ListModelsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListModelsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListModelsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListModelsResponse := _ListModelsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListModelsResponse)

	if err != nil {
		return err
	}

	*o = ListModelsResponse(varListModelsResponse)

	return err
}

type NullableListModelsResponse struct {
	value *ListModelsResponse
	isSet bool
}

func (v NullableListModelsResponse) Get() *ListModelsResponse {
	return v.value
}

func (v *NullableListModelsResponse) Set(val *ListModelsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListModelsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListModelsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListModelsResponse(val *ListModelsResponse) *NullableListModelsResponse {
	return &NullableListModelsResponse{value: val, isSet: true}
}

func (v NullableListModelsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListModelsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


