/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompletionInputType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompletionInputType{}

// CompletionInputType struct for CompletionInputType
type CompletionInputType struct {
	Type string `json:"type"`
}

type _CompletionInputType CompletionInputType

// NewCompletionInputType instantiates a new CompletionInputType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompletionInputType(type_ string) *CompletionInputType {
	this := CompletionInputType{}
	this.Type = type_
	return &this
}

// NewCompletionInputTypeWithDefaults instantiates a new CompletionInputType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompletionInputTypeWithDefaults() *CompletionInputType {
	this := CompletionInputType{}
	var type_ string = "completion_input"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *CompletionInputType) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CompletionInputType) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CompletionInputType) SetType(v string) {
	o.Type = v
}

func (o CompletionInputType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompletionInputType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *CompletionInputType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompletionInputType := _CompletionInputType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompletionInputType)

	if err != nil {
		return err
	}

	*o = CompletionInputType(varCompletionInputType)

	return err
}

type NullableCompletionInputType struct {
	value *CompletionInputType
	isSet bool
}

func (v NullableCompletionInputType) Get() *CompletionInputType {
	return v.value
}

func (v *NullableCompletionInputType) Set(val *CompletionInputType) {
	v.value = val
	v.isSet = true
}

func (v NullableCompletionInputType) IsSet() bool {
	return v.isSet
}

func (v *NullableCompletionInputType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompletionInputType(val *CompletionInputType) *NullableCompletionInputType {
	return &NullableCompletionInputType{value: val, isSet: true}
}

func (v NullableCompletionInputType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompletionInputType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


