/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SyntheticDataGenerateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyntheticDataGenerateRequest{}

// SyntheticDataGenerateRequest struct for SyntheticDataGenerateRequest
type SyntheticDataGenerateRequest struct {
	Dialogs []Message `json:"dialogs"`
	// The type of filtering function.
	FilteringFunction string `json:"filtering_function"`
	Model *string `json:"model,omitempty"`
}

type _SyntheticDataGenerateRequest SyntheticDataGenerateRequest

// NewSyntheticDataGenerateRequest instantiates a new SyntheticDataGenerateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyntheticDataGenerateRequest(dialogs []Message, filteringFunction string) *SyntheticDataGenerateRequest {
	this := SyntheticDataGenerateRequest{}
	this.Dialogs = dialogs
	this.FilteringFunction = filteringFunction
	return &this
}

// NewSyntheticDataGenerateRequestWithDefaults instantiates a new SyntheticDataGenerateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyntheticDataGenerateRequestWithDefaults() *SyntheticDataGenerateRequest {
	this := SyntheticDataGenerateRequest{}
	return &this
}

// GetDialogs returns the Dialogs field value
func (o *SyntheticDataGenerateRequest) GetDialogs() []Message {
	if o == nil {
		var ret []Message
		return ret
	}

	return o.Dialogs
}

// GetDialogsOk returns a tuple with the Dialogs field value
// and a boolean to check if the value has been set.
func (o *SyntheticDataGenerateRequest) GetDialogsOk() ([]Message, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dialogs, true
}

// SetDialogs sets field value
func (o *SyntheticDataGenerateRequest) SetDialogs(v []Message) {
	o.Dialogs = v
}

// GetFilteringFunction returns the FilteringFunction field value
func (o *SyntheticDataGenerateRequest) GetFilteringFunction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilteringFunction
}

// GetFilteringFunctionOk returns a tuple with the FilteringFunction field value
// and a boolean to check if the value has been set.
func (o *SyntheticDataGenerateRequest) GetFilteringFunctionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilteringFunction, true
}

// SetFilteringFunction sets field value
func (o *SyntheticDataGenerateRequest) SetFilteringFunction(v string) {
	o.FilteringFunction = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *SyntheticDataGenerateRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyntheticDataGenerateRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *SyntheticDataGenerateRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *SyntheticDataGenerateRequest) SetModel(v string) {
	o.Model = &v
}

func (o SyntheticDataGenerateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyntheticDataGenerateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dialogs"] = o.Dialogs
	toSerialize["filtering_function"] = o.FilteringFunction
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	return toSerialize, nil
}

func (o *SyntheticDataGenerateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dialogs",
		"filtering_function",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyntheticDataGenerateRequest := _SyntheticDataGenerateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyntheticDataGenerateRequest)

	if err != nil {
		return err
	}

	*o = SyntheticDataGenerateRequest(varSyntheticDataGenerateRequest)

	return err
}

type NullableSyntheticDataGenerateRequest struct {
	value *SyntheticDataGenerateRequest
	isSet bool
}

func (v NullableSyntheticDataGenerateRequest) Get() *SyntheticDataGenerateRequest {
	return v.value
}

func (v *NullableSyntheticDataGenerateRequest) Set(val *SyntheticDataGenerateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSyntheticDataGenerateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSyntheticDataGenerateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyntheticDataGenerateRequest(val *SyntheticDataGenerateRequest) *NullableSyntheticDataGenerateRequest {
	return &NullableSyntheticDataGenerateRequest{value: val, isSet: true}
}

func (v NullableSyntheticDataGenerateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyntheticDataGenerateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


