/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentStepResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentStepResponse{}

// AgentStepResponse struct for AgentStepResponse
type AgentStepResponse struct {
	Step TurnStepsInner `json:"step"`
}

type _AgentStepResponse AgentStepResponse

// NewAgentStepResponse instantiates a new AgentStepResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentStepResponse(step TurnStepsInner) *AgentStepResponse {
	this := AgentStepResponse{}
	this.Step = step
	return &this
}

// NewAgentStepResponseWithDefaults instantiates a new AgentStepResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentStepResponseWithDefaults() *AgentStepResponse {
	this := AgentStepResponse{}
	return &this
}

// GetStep returns the Step field value
func (o *AgentStepResponse) GetStep() TurnStepsInner {
	if o == nil {
		var ret TurnStepsInner
		return ret
	}

	return o.Step
}

// GetStepOk returns a tuple with the Step field value
// and a boolean to check if the value has been set.
func (o *AgentStepResponse) GetStepOk() (*TurnStepsInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Step, true
}

// SetStep sets field value
func (o *AgentStepResponse) SetStep(v TurnStepsInner) {
	o.Step = v
}

func (o AgentStepResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentStepResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["step"] = o.Step
	return toSerialize, nil
}

func (o *AgentStepResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"step",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentStepResponse := _AgentStepResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentStepResponse)

	if err != nil {
		return err
	}

	*o = AgentStepResponse(varAgentStepResponse)

	return err
}

type NullableAgentStepResponse struct {
	value *AgentStepResponse
	isSet bool
}

func (v NullableAgentStepResponse) Get() *AgentStepResponse {
	return v.value
}

func (v *NullableAgentStepResponse) Set(val *AgentStepResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentStepResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentStepResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentStepResponse(val *AgentStepResponse) *NullableAgentStepResponse {
	return &NullableAgentStepResponse{value: val, isSet: true}
}

func (v NullableAgentStepResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentStepResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


