/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenAISystemMessageParam type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenAISystemMessageParam{}

// OpenAISystemMessageParam A system message providing instructions or context to the model.
type OpenAISystemMessageParam struct {
	// Must be \"system\" to identify this as a system message
	Role string `json:"role"`
	Content OpenAISystemMessageParamContent `json:"content"`
	// (Optional) The name of the system message participant.
	Name *string `json:"name,omitempty"`
}

type _OpenAISystemMessageParam OpenAISystemMessageParam

// NewOpenAISystemMessageParam instantiates a new OpenAISystemMessageParam object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenAISystemMessageParam(role string, content OpenAISystemMessageParamContent) *OpenAISystemMessageParam {
	this := OpenAISystemMessageParam{}
	this.Role = role
	this.Content = content
	return &this
}

// NewOpenAISystemMessageParamWithDefaults instantiates a new OpenAISystemMessageParam object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenAISystemMessageParamWithDefaults() *OpenAISystemMessageParam {
	this := OpenAISystemMessageParam{}
	var role string = "system"
	this.Role = role
	return &this
}

// GetRole returns the Role field value
func (o *OpenAISystemMessageParam) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *OpenAISystemMessageParam) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *OpenAISystemMessageParam) SetRole(v string) {
	o.Role = v
}

// GetContent returns the Content field value
func (o *OpenAISystemMessageParam) GetContent() OpenAISystemMessageParamContent {
	if o == nil {
		var ret OpenAISystemMessageParamContent
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *OpenAISystemMessageParam) GetContentOk() (*OpenAISystemMessageParamContent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *OpenAISystemMessageParam) SetContent(v OpenAISystemMessageParamContent) {
	o.Content = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OpenAISystemMessageParam) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenAISystemMessageParam) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OpenAISystemMessageParam) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OpenAISystemMessageParam) SetName(v string) {
	o.Name = &v
}

func (o OpenAISystemMessageParam) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenAISystemMessageParam) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	toSerialize["content"] = o.Content
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

func (o *OpenAISystemMessageParam) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenAISystemMessageParam := _OpenAISystemMessageParam{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenAISystemMessageParam)

	if err != nil {
		return err
	}

	*o = OpenAISystemMessageParam(varOpenAISystemMessageParam)

	return err
}

type NullableOpenAISystemMessageParam struct {
	value *OpenAISystemMessageParam
	isSet bool
}

func (v NullableOpenAISystemMessageParam) Get() *OpenAISystemMessageParam {
	return v.value
}

func (v *NullableOpenAISystemMessageParam) Set(val *OpenAISystemMessageParam) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenAISystemMessageParam) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenAISystemMessageParam) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenAISystemMessageParam(val *OpenAISystemMessageParam) *NullableOpenAISystemMessageParam {
	return &NullableOpenAISystemMessageParam{value: val, isSet: true}
}

func (v NullableOpenAISystemMessageParam) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenAISystemMessageParam) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


