/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AgentSessionCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentSessionCreateResponse{}

// AgentSessionCreateResponse struct for AgentSessionCreateResponse
type AgentSessionCreateResponse struct {
	SessionId string `json:"session_id"`
}

type _AgentSessionCreateResponse AgentSessionCreateResponse

// NewAgentSessionCreateResponse instantiates a new AgentSessionCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentSessionCreateResponse(sessionId string) *AgentSessionCreateResponse {
	this := AgentSessionCreateResponse{}
	this.SessionId = sessionId
	return &this
}

// NewAgentSessionCreateResponseWithDefaults instantiates a new AgentSessionCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentSessionCreateResponseWithDefaults() *AgentSessionCreateResponse {
	this := AgentSessionCreateResponse{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *AgentSessionCreateResponse) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *AgentSessionCreateResponse) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *AgentSessionCreateResponse) SetSessionId(v string) {
	o.SessionId = v
}

func (o AgentSessionCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentSessionCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["session_id"] = o.SessionId
	return toSerialize, nil
}

func (o *AgentSessionCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentSessionCreateResponse := _AgentSessionCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentSessionCreateResponse)

	if err != nil {
		return err
	}

	*o = AgentSessionCreateResponse(varAgentSessionCreateResponse)

	return err
}

type NullableAgentSessionCreateResponse struct {
	value *AgentSessionCreateResponse
	isSet bool
}

func (v NullableAgentSessionCreateResponse) Get() *AgentSessionCreateResponse {
	return v.value
}

func (v *NullableAgentSessionCreateResponse) Set(val *AgentSessionCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentSessionCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentSessionCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentSessionCreateResponse(val *AgentSessionCreateResponse) *NullableAgentSessionCreateResponse {
	return &NullableAgentSessionCreateResponse{value: val, isSet: true}
}

func (v NullableAgentSessionCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentSessionCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


