/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Shield type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Shield{}

// Shield A safety shield resource that can be used to check content
type Shield struct {
	Identifier string `json:"identifier"`
	ProviderResourceId string `json:"provider_resource_id"`
	ProviderId string `json:"provider_id"`
	Type string `json:"type"`
	Params map[string]AppendRowsRequestRowsInnerValue `json:"params,omitempty"`
}

type _Shield Shield

// NewShield instantiates a new Shield object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShield(identifier string, providerResourceId string, providerId string, type_ string) *Shield {
	this := Shield{}
	this.Identifier = identifier
	this.ProviderResourceId = providerResourceId
	this.ProviderId = providerId
	this.Type = type_
	return &this
}

// NewShieldWithDefaults instantiates a new Shield object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShieldWithDefaults() *Shield {
	this := Shield{}
	var type_ string = "shield"
	this.Type = type_
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *Shield) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *Shield) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *Shield) SetIdentifier(v string) {
	o.Identifier = v
}

// GetProviderResourceId returns the ProviderResourceId field value
func (o *Shield) GetProviderResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderResourceId
}

// GetProviderResourceIdOk returns a tuple with the ProviderResourceId field value
// and a boolean to check if the value has been set.
func (o *Shield) GetProviderResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderResourceId, true
}

// SetProviderResourceId sets field value
func (o *Shield) SetProviderResourceId(v string) {
	o.ProviderResourceId = v
}

// GetProviderId returns the ProviderId field value
func (o *Shield) GetProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *Shield) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *Shield) SetProviderId(v string) {
	o.ProviderId = v
}

// GetType returns the Type field value
func (o *Shield) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Shield) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Shield) SetType(v string) {
	o.Type = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *Shield) GetParams() map[string]AppendRowsRequestRowsInnerValue {
	if o == nil || IsNil(o.Params) {
		var ret map[string]AppendRowsRequestRowsInnerValue
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Shield) GetParamsOk() (map[string]AppendRowsRequestRowsInnerValue, bool) {
	if o == nil || IsNil(o.Params) {
		return map[string]AppendRowsRequestRowsInnerValue{}, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *Shield) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given map[string]AppendRowsRequestRowsInnerValue and assigns it to the Params field.
func (o *Shield) SetParams(v map[string]AppendRowsRequestRowsInnerValue) {
	o.Params = v
}

func (o Shield) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Shield) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	toSerialize["provider_resource_id"] = o.ProviderResourceId
	toSerialize["provider_id"] = o.ProviderId
	toSerialize["type"] = o.Type
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	return toSerialize, nil
}

func (o *Shield) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"identifier",
		"provider_resource_id",
		"provider_id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShield := _Shield{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShield)

	if err != nil {
		return err
	}

	*o = Shield(varShield)

	return err
}

type NullableShield struct {
	value *Shield
	isSet bool
}

func (v NullableShield) Get() *Shield {
	return v.value
}

func (v *NullableShield) Set(val *Shield) {
	v.value = val
	v.isSet = true
}

func (v NullableShield) IsSet() bool {
	return v.isSet
}

func (v *NullableShield) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShield(val *Shield) *NullableShield {
	return &NullableShield{value: val, isSet: true}
}

func (v NullableShield) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShield) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


