/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenAIResponseFormatJSONSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenAIResponseFormatJSONSchema{}

// OpenAIResponseFormatJSONSchema struct for OpenAIResponseFormatJSONSchema
type OpenAIResponseFormatJSONSchema struct {
	Type string `json:"type"`
	JsonSchema OpenAIJSONSchema `json:"json_schema"`
}

type _OpenAIResponseFormatJSONSchema OpenAIResponseFormatJSONSchema

// NewOpenAIResponseFormatJSONSchema instantiates a new OpenAIResponseFormatJSONSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenAIResponseFormatJSONSchema(type_ string, jsonSchema OpenAIJSONSchema) *OpenAIResponseFormatJSONSchema {
	this := OpenAIResponseFormatJSONSchema{}
	this.Type = type_
	this.JsonSchema = jsonSchema
	return &this
}

// NewOpenAIResponseFormatJSONSchemaWithDefaults instantiates a new OpenAIResponseFormatJSONSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenAIResponseFormatJSONSchemaWithDefaults() *OpenAIResponseFormatJSONSchema {
	this := OpenAIResponseFormatJSONSchema{}
	var type_ string = "json_schema"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *OpenAIResponseFormatJSONSchema) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OpenAIResponseFormatJSONSchema) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OpenAIResponseFormatJSONSchema) SetType(v string) {
	o.Type = v
}

// GetJsonSchema returns the JsonSchema field value
func (o *OpenAIResponseFormatJSONSchema) GetJsonSchema() OpenAIJSONSchema {
	if o == nil {
		var ret OpenAIJSONSchema
		return ret
	}

	return o.JsonSchema
}

// GetJsonSchemaOk returns a tuple with the JsonSchema field value
// and a boolean to check if the value has been set.
func (o *OpenAIResponseFormatJSONSchema) GetJsonSchemaOk() (*OpenAIJSONSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JsonSchema, true
}

// SetJsonSchema sets field value
func (o *OpenAIResponseFormatJSONSchema) SetJsonSchema(v OpenAIJSONSchema) {
	o.JsonSchema = v
}

func (o OpenAIResponseFormatJSONSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenAIResponseFormatJSONSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["json_schema"] = o.JsonSchema
	return toSerialize, nil
}

func (o *OpenAIResponseFormatJSONSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"json_schema",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenAIResponseFormatJSONSchema := _OpenAIResponseFormatJSONSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenAIResponseFormatJSONSchema)

	if err != nil {
		return err
	}

	*o = OpenAIResponseFormatJSONSchema(varOpenAIResponseFormatJSONSchema)

	return err
}

type NullableOpenAIResponseFormatJSONSchema struct {
	value *OpenAIResponseFormatJSONSchema
	isSet bool
}

func (v NullableOpenAIResponseFormatJSONSchema) Get() *OpenAIResponseFormatJSONSchema {
	return v.value
}

func (v *NullableOpenAIResponseFormatJSONSchema) Set(val *OpenAIResponseFormatJSONSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenAIResponseFormatJSONSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenAIResponseFormatJSONSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenAIResponseFormatJSONSchema(val *OpenAIResponseFormatJSONSchema) *NullableOpenAIResponseFormatJSONSchema {
	return &NullableOpenAIResponseFormatJSONSchema{value: val, isSet: true}
}

func (v NullableOpenAIResponseFormatJSONSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenAIResponseFormatJSONSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


