/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CancelTrainingJobRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelTrainingJobRequest{}

// CancelTrainingJobRequest struct for CancelTrainingJobRequest
type CancelTrainingJobRequest struct {
	JobUuid string `json:"job_uuid"`
}

type _CancelTrainingJobRequest CancelTrainingJobRequest

// NewCancelTrainingJobRequest instantiates a new CancelTrainingJobRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelTrainingJobRequest(jobUuid string) *CancelTrainingJobRequest {
	this := CancelTrainingJobRequest{}
	this.JobUuid = jobUuid
	return &this
}

// NewCancelTrainingJobRequestWithDefaults instantiates a new CancelTrainingJobRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelTrainingJobRequestWithDefaults() *CancelTrainingJobRequest {
	this := CancelTrainingJobRequest{}
	return &this
}

// GetJobUuid returns the JobUuid field value
func (o *CancelTrainingJobRequest) GetJobUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobUuid
}

// GetJobUuidOk returns a tuple with the JobUuid field value
// and a boolean to check if the value has been set.
func (o *CancelTrainingJobRequest) GetJobUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobUuid, true
}

// SetJobUuid sets field value
func (o *CancelTrainingJobRequest) SetJobUuid(v string) {
	o.JobUuid = v
}

func (o CancelTrainingJobRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelTrainingJobRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_uuid"] = o.JobUuid
	return toSerialize, nil
}

func (o *CancelTrainingJobRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_uuid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelTrainingJobRequest := _CancelTrainingJobRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelTrainingJobRequest)

	if err != nil {
		return err
	}

	*o = CancelTrainingJobRequest(varCancelTrainingJobRequest)

	return err
}

type NullableCancelTrainingJobRequest struct {
	value *CancelTrainingJobRequest
	isSet bool
}

func (v NullableCancelTrainingJobRequest) Get() *CancelTrainingJobRequest {
	return v.value
}

func (v *NullableCancelTrainingJobRequest) Set(val *CancelTrainingJobRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelTrainingJobRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelTrainingJobRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelTrainingJobRequest(val *CancelTrainingJobRequest) *NullableCancelTrainingJobRequest {
	return &NullableCancelTrainingJobRequest{value: val, isSet: true}
}

func (v NullableCancelTrainingJobRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelTrainingJobRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


