/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScoreResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScoreResponse{}

// ScoreResponse The response from scoring.
type ScoreResponse struct {
	// A map of scoring function name to ScoringResult.
	Results map[string]ScoringResult `json:"results"`
}

type _ScoreResponse ScoreResponse

// NewScoreResponse instantiates a new ScoreResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScoreResponse(results map[string]ScoringResult) *ScoreResponse {
	this := ScoreResponse{}
	this.Results = results
	return &this
}

// NewScoreResponseWithDefaults instantiates a new ScoreResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScoreResponseWithDefaults() *ScoreResponse {
	this := ScoreResponse{}
	return &this
}

// GetResults returns the Results field value
func (o *ScoreResponse) GetResults() map[string]ScoringResult {
	if o == nil {
		var ret map[string]ScoringResult
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *ScoreResponse) GetResultsOk() (map[string]ScoringResult, bool) {
	if o == nil {
		return map[string]ScoringResult{}, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *ScoreResponse) SetResults(v map[string]ScoringResult) {
	o.Results = v
}

func (o ScoreResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScoreResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *ScoreResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScoreResponse := _ScoreResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScoreResponse)

	if err != nil {
		return err
	}

	*o = ScoreResponse(varScoreResponse)

	return err
}

type NullableScoreResponse struct {
	value *ScoreResponse
	isSet bool
}

func (v NullableScoreResponse) Get() *ScoreResponse {
	return v.value
}

func (v *NullableScoreResponse) Set(val *ScoreResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableScoreResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableScoreResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScoreResponse(val *ScoreResponse) *NullableScoreResponse {
	return &NullableScoreResponse{value: val, isSet: true}
}

func (v NullableScoreResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScoreResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


