/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// MetricInResponseValue - struct for MetricInResponseValue
type MetricInResponseValue struct {
	Float32 *float32
	Int32 *int32
}

// float32AsMetricInResponseValue is a convenience function that returns float32 wrapped in MetricInResponseValue
func Float32AsMetricInResponseValue(v *float32) MetricInResponseValue {
	return MetricInResponseValue{
		Float32: v,
	}
}

// int32AsMetricInResponseValue is a convenience function that returns int32 wrapped in MetricInResponseValue
func Int32AsMetricInResponseValue(v *int32) MetricInResponseValue {
	return MetricInResponseValue{
		Int32: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *MetricInResponseValue) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Float32
	err = newStrictDecoder(data).Decode(&dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			if err = validator.Validate(dst.Float32); err != nil {
				dst.Float32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Float32 = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(MetricInResponseValue)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(MetricInResponseValue)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MetricInResponseValue) MarshalJSON() ([]byte, error) {
	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MetricInResponseValue) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Float32 != nil {
		return obj.Float32
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj MetricInResponseValue) GetActualInstanceValue() (interface{}) {
	if obj.Float32 != nil {
		return *obj.Float32
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableMetricInResponseValue struct {
	value *MetricInResponseValue
	isSet bool
}

func (v NullableMetricInResponseValue) Get() *MetricInResponseValue {
	return v.value
}

func (v *NullableMetricInResponseValue) Set(val *MetricInResponseValue) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricInResponseValue) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricInResponseValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricInResponseValue(val *MetricInResponseValue) *NullableMetricInResponseValue {
	return &NullableMetricInResponseValue{value: val, isSet: true}
}

func (v NullableMetricInResponseValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricInResponseValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


