/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ToolCallToolName - struct for ToolCallToolName
type ToolCallToolName struct {
	String *string
}

// stringAsToolCallToolName is a convenience function that returns string wrapped in ToolCallToolName
func StringAsToolCallToolName(v *string) ToolCallToolName {
	return ToolCallToolName{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ToolCallToolName) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ToolCallToolName)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ToolCallToolName)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ToolCallToolName) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ToolCallToolName) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ToolCallToolName) GetActualInstanceValue() (interface{}) {
	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableToolCallToolName struct {
	value *ToolCallToolName
	isSet bool
}

func (v NullableToolCallToolName) Get() *ToolCallToolName {
	return v.value
}

func (v *NullableToolCallToolName) Set(val *ToolCallToolName) {
	v.value = val
	v.isSet = true
}

func (v NullableToolCallToolName) IsSet() bool {
	return v.isSet
}

func (v *NullableToolCallToolName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToolCallToolName(val *ToolCallToolName) *NullableToolCallToolName {
	return &NullableToolCallToolName{value: val, isSet: true}
}

func (v NullableToolCallToolName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToolCallToolName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


