/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GreedySamplingStrategy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GreedySamplingStrategy{}

// GreedySamplingStrategy struct for GreedySamplingStrategy
type GreedySamplingStrategy struct {
	Type string `json:"type"`
}

type _GreedySamplingStrategy GreedySamplingStrategy

// NewGreedySamplingStrategy instantiates a new GreedySamplingStrategy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGreedySamplingStrategy(type_ string) *GreedySamplingStrategy {
	this := GreedySamplingStrategy{}
	this.Type = type_
	return &this
}

// NewGreedySamplingStrategyWithDefaults instantiates a new GreedySamplingStrategy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGreedySamplingStrategyWithDefaults() *GreedySamplingStrategy {
	this := GreedySamplingStrategy{}
	var type_ string = "greedy"
	this.Type = type_
	return &this
}

// GetType returns the Type field value
func (o *GreedySamplingStrategy) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GreedySamplingStrategy) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GreedySamplingStrategy) SetType(v string) {
	o.Type = v
}

func (o GreedySamplingStrategy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GreedySamplingStrategy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *GreedySamplingStrategy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGreedySamplingStrategy := _GreedySamplingStrategy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGreedySamplingStrategy)

	if err != nil {
		return err
	}

	*o = GreedySamplingStrategy(varGreedySamplingStrategy)

	return err
}

type NullableGreedySamplingStrategy struct {
	value *GreedySamplingStrategy
	isSet bool
}

func (v NullableGreedySamplingStrategy) Get() *GreedySamplingStrategy {
	return v.value
}

func (v *NullableGreedySamplingStrategy) Set(val *GreedySamplingStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableGreedySamplingStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableGreedySamplingStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGreedySamplingStrategy(val *GreedySamplingStrategy) *NullableGreedySamplingStrategy {
	return &NullableGreedySamplingStrategy{value: val, isSet: true}
}

func (v NullableGreedySamplingStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGreedySamplingStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


