/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RAGDocumentContent - The content of the document.
type RAGDocumentContent struct {
	InterleavedContentItem *InterleavedContentItem
	URL *URL
	ArrayOfInterleavedContentItem *[]InterleavedContentItem
	String *string
}

// InterleavedContentItemAsRAGDocumentContent is a convenience function that returns InterleavedContentItem wrapped in RAGDocumentContent
func InterleavedContentItemAsRAGDocumentContent(v *InterleavedContentItem) RAGDocumentContent {
	return RAGDocumentContent{
		InterleavedContentItem: v,
	}
}

// URLAsRAGDocumentContent is a convenience function that returns URL wrapped in RAGDocumentContent
func URLAsRAGDocumentContent(v *URL) RAGDocumentContent {
	return RAGDocumentContent{
		URL: v,
	}
}

// []InterleavedContentItemAsRAGDocumentContent is a convenience function that returns []InterleavedContentItem wrapped in RAGDocumentContent
func ArrayOfInterleavedContentItemAsRAGDocumentContent(v *[]InterleavedContentItem) RAGDocumentContent {
	return RAGDocumentContent{
		ArrayOfInterleavedContentItem: v,
	}
}

// stringAsRAGDocumentContent is a convenience function that returns string wrapped in RAGDocumentContent
func StringAsRAGDocumentContent(v *string) RAGDocumentContent {
	return RAGDocumentContent{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RAGDocumentContent) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into InterleavedContentItem
	err = newStrictDecoder(data).Decode(&dst.InterleavedContentItem)
	if err == nil {
		jsonInterleavedContentItem, _ := json.Marshal(dst.InterleavedContentItem)
		if string(jsonInterleavedContentItem) == "{}" { // empty struct
			dst.InterleavedContentItem = nil
		} else {
			if err = validator.Validate(dst.InterleavedContentItem); err != nil {
				dst.InterleavedContentItem = nil
			} else {
				match++
			}
		}
	} else {
		dst.InterleavedContentItem = nil
	}

	// try to unmarshal data into URL
	err = newStrictDecoder(data).Decode(&dst.URL)
	if err == nil {
		jsonURL, _ := json.Marshal(dst.URL)
		if string(jsonURL) == "{}" { // empty struct
			dst.URL = nil
		} else {
			if err = validator.Validate(dst.URL); err != nil {
				dst.URL = nil
			} else {
				match++
			}
		}
	} else {
		dst.URL = nil
	}

	// try to unmarshal data into ArrayOfInterleavedContentItem
	err = newStrictDecoder(data).Decode(&dst.ArrayOfInterleavedContentItem)
	if err == nil {
		jsonArrayOfInterleavedContentItem, _ := json.Marshal(dst.ArrayOfInterleavedContentItem)
		if string(jsonArrayOfInterleavedContentItem) == "{}" { // empty struct
			dst.ArrayOfInterleavedContentItem = nil
		} else {
			if err = validator.Validate(dst.ArrayOfInterleavedContentItem); err != nil {
				dst.ArrayOfInterleavedContentItem = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfInterleavedContentItem = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.InterleavedContentItem = nil
		dst.URL = nil
		dst.ArrayOfInterleavedContentItem = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RAGDocumentContent)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RAGDocumentContent)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RAGDocumentContent) MarshalJSON() ([]byte, error) {
	if src.InterleavedContentItem != nil {
		return json.Marshal(&src.InterleavedContentItem)
	}

	if src.URL != nil {
		return json.Marshal(&src.URL)
	}

	if src.ArrayOfInterleavedContentItem != nil {
		return json.Marshal(&src.ArrayOfInterleavedContentItem)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RAGDocumentContent) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.InterleavedContentItem != nil {
		return obj.InterleavedContentItem
	}

	if obj.URL != nil {
		return obj.URL
	}

	if obj.ArrayOfInterleavedContentItem != nil {
		return obj.ArrayOfInterleavedContentItem
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RAGDocumentContent) GetActualInstanceValue() (interface{}) {
	if obj.InterleavedContentItem != nil {
		return *obj.InterleavedContentItem
	}

	if obj.URL != nil {
		return *obj.URL
	}

	if obj.ArrayOfInterleavedContentItem != nil {
		return *obj.ArrayOfInterleavedContentItem
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableRAGDocumentContent struct {
	value *RAGDocumentContent
	isSet bool
}

func (v NullableRAGDocumentContent) Get() *RAGDocumentContent {
	return v.value
}

func (v *NullableRAGDocumentContent) Set(val *RAGDocumentContent) {
	v.value = val
	v.isSet = true
}

func (v NullableRAGDocumentContent) IsSet() bool {
	return v.isSet
}

func (v *NullableRAGDocumentContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRAGDocumentContent(val *RAGDocumentContent) *NullableRAGDocumentContent {
	return &NullableRAGDocumentContent{value: val, isSet: true}
}

func (v NullableRAGDocumentContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRAGDocumentContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


