/*
Llama Stack Specification

This is the specification of the Llama Stack that provides                 a set of endpoints and their corresponding interfaces that are tailored to                 best leverage Llama Models.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostTrainingJobArtifactsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTrainingJobArtifactsResponse{}

// PostTrainingJobArtifactsResponse Artifacts of a finetuning job.
type PostTrainingJobArtifactsResponse struct {
	JobUuid string `json:"job_uuid"`
	Checkpoints []interface{} `json:"checkpoints"`
}

type _PostTrainingJobArtifactsResponse PostTrainingJobArtifactsResponse

// NewPostTrainingJobArtifactsResponse instantiates a new PostTrainingJobArtifactsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTrainingJobArtifactsResponse(jobUuid string, checkpoints []interface{}) *PostTrainingJobArtifactsResponse {
	this := PostTrainingJobArtifactsResponse{}
	this.JobUuid = jobUuid
	this.Checkpoints = checkpoints
	return &this
}

// NewPostTrainingJobArtifactsResponseWithDefaults instantiates a new PostTrainingJobArtifactsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTrainingJobArtifactsResponseWithDefaults() *PostTrainingJobArtifactsResponse {
	this := PostTrainingJobArtifactsResponse{}
	return &this
}

// GetJobUuid returns the JobUuid field value
func (o *PostTrainingJobArtifactsResponse) GetJobUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobUuid
}

// GetJobUuidOk returns a tuple with the JobUuid field value
// and a boolean to check if the value has been set.
func (o *PostTrainingJobArtifactsResponse) GetJobUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobUuid, true
}

// SetJobUuid sets field value
func (o *PostTrainingJobArtifactsResponse) SetJobUuid(v string) {
	o.JobUuid = v
}

// GetCheckpoints returns the Checkpoints field value
func (o *PostTrainingJobArtifactsResponse) GetCheckpoints() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Checkpoints
}

// GetCheckpointsOk returns a tuple with the Checkpoints field value
// and a boolean to check if the value has been set.
func (o *PostTrainingJobArtifactsResponse) GetCheckpointsOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Checkpoints, true
}

// SetCheckpoints sets field value
func (o *PostTrainingJobArtifactsResponse) SetCheckpoints(v []interface{}) {
	o.Checkpoints = v
}

func (o PostTrainingJobArtifactsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTrainingJobArtifactsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_uuid"] = o.JobUuid
	toSerialize["checkpoints"] = o.Checkpoints
	return toSerialize, nil
}

func (o *PostTrainingJobArtifactsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_uuid",
		"checkpoints",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostTrainingJobArtifactsResponse := _PostTrainingJobArtifactsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostTrainingJobArtifactsResponse)

	if err != nil {
		return err
	}

	*o = PostTrainingJobArtifactsResponse(varPostTrainingJobArtifactsResponse)

	return err
}

type NullablePostTrainingJobArtifactsResponse struct {
	value *PostTrainingJobArtifactsResponse
	isSet bool
}

func (v NullablePostTrainingJobArtifactsResponse) Get() *PostTrainingJobArtifactsResponse {
	return v.value
}

func (v *NullablePostTrainingJobArtifactsResponse) Set(val *PostTrainingJobArtifactsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTrainingJobArtifactsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTrainingJobArtifactsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTrainingJobArtifactsResponse(val *PostTrainingJobArtifactsResponse) *NullablePostTrainingJobArtifactsResponse {
	return &NullablePostTrainingJobArtifactsResponse{value: val, isSet: true}
}

func (v NullablePostTrainingJobArtifactsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTrainingJobArtifactsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


